spring:
  datasource:
    url: jdbc:mysql://localhost:3306/code_db?useUnicode=true&characterEncoding=utf-8&noAccessToProcedureBodies=true&rewriteBatchedStatements=true&useAffectedRows=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
